# ansible/deploy.yml
---
- name: Deploy Java Web App to Local Minikube
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Kubernetes Deployment and Service Manifests
      kubernetes.core.k8s:
        src: ../k8s/deployment.yml
        state: present

    - name: Force Rolling Update to Pull Fresh Images
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: githubemc1-deployment
            namespace: default
          spec:
            template:
              metadata:
                annotations:
                  rollout-timestamp: "{{ ansible_date_time.iso8601 }}"